### ISSUE TITLE
Integração com WooCommerce Subscriptions

### ISSUE THREAD

**Issue by giovannicocco** [pagarme/woocommerce#114]
Criar a integração com Woocommerce Subscription visto que somente os big players como Stripe e Paypal utilizam, porém unificar tudo em um único meio de pagamento nacional seria mais interessante.

**Comment by santanamic** [comment]
> Criar a integração com Woocommerce Subscription visto que somente os big players como Stripe e Paypal utilizam, porém unificar tudo em um único meio de pagamento nacional seria mais interessante.

Essa empresa [https://www.aquarela.cc/](url) desenvolve integrações personalizas. Eles tem a integração do pagar.me (cartão de credito) para  WooCommerce Subscriptions. Entre em contato e peça uma demonstração.

**Comment by aguiarrdev** [comment]
@giovannicocco A Vindi possui integração com WC Subscriptions

**Comment by RafaMelazzo** [comment]
Olá @giovannicocco!

Disponibilizamos essa integração na versão 3.1 do nosso módulo. Você pode atualizar e começar a utilizar essa funcionalidade.

Caso precise de alguma ajuda, contate o suporte no [relacionamento@pagar.me](mailto:relacionamento@pagar.me)
