### ISSUE TITLE
Existe alguma forma de melhorar a aparência do Checkout?

### ISSUE THREAD

**Issue by rubenssoto** [pagarme/woocommerce#171]
Boa Noite, tudo bem?

Existe algum forma de melhorar a aparência do checkout?
A sensação que dá é que a tela da pagar.me não faz parte do checkout, não segue o design do tema.

**Comment by odirlon** [comment]
Oi, veja se o seguinte css lhe ajuda: 

`.payment_box.panel.entry-content.pagarme_methods {
    display: block!important;
}li.wc_payment_method.pagarme-method > label {
    display: none!important;
}.pagarme-method label {
    padding-top: 0em !important;
    padding-bottom: 0em !important;
}label[for="payment_method_woo-pagarme-payments"] {
    padding-bottom: 14px!important;
}.payment_box.payment_method_woo-pagarme-payments ul.wc_payment_methods.payment_methods.methods {
    border: 0px solid #e2e2e2;
}.payment_box.panel.entry-content.pagarme_methods .form-row input.input-text {
    border-color: #a1a1a1!important;
    border-width: 1px!important;
    border-radius: 0.3rem!important;
    box-shadow: 0 1px 2px 0 rgb(0 0 0 / 5%)!important;
    font-size: 14px!important;
    padding: 8px!important;
}#payment .payment_methods li .payment_box fieldset .form-row {
    margin-bottom: 5px;
}select#installments_card {
    font-size: 1.1em!important;
}`

Da pra melhorar, outro ponto, não usamos o pix nem boleto do pagar-me então ali ocultamos alguns detalhes, adapte ao seu uso. 

Seria uma dica para o pagarme inserir os métodos de pagamento deles de forma separada. Cada método como um método destinto para poder manter a ordem no checkout. No meu caso é indiferente pois só uso o cartão.

**Comment by rubenssoto** [comment]
Vou testar o CSS, muito obrigado.

Mas mesmo sendo possível "ajeitar" com CSS, deve ter algo que o próprio plugin poderia fazer pra melhorar, pq não tenho problema em relação a isso com nenhum plugin de pagamento.

**Comment by odirlon** [comment]
Parece que eles seguiram o layout do storefront em vez de deixar as tags
livres pra seguir o estilo dos temas. Mas é tranquilo customizar. Eu fiz
com base no que usamos. Mas fiz bem meia boca tb...

Em qui., 12 de jan. de 2023 21:10, rubenssoto ***@***.***>
escreveu:

**Comment by mateus-picoloto** [comment]
Bom dia @rubenssoto, tudo bem?

Na versão [3.0.0](https://github.com/pagarme/woocommerce/releases/tag/3.0.0) do plugin foi alterado para compatibilizar com os css dos temas.

Caso o problema ainda persista favor reabrir a issue.

Muito obrigado!
