### ISSUE TITLE
Split de pagamentos

### ISSUE THREAD

**Issue by AlissonIC** [pagarme/woocommerce#207]
Boa tarde tudo bem?

Achei algumas referencias ao split de pamentos, é possivel estender alguma função para criar um split com 2 ou mais recebedores?

**Comment by jfernando1599** [comment]
Eu também estou precisando disso. Quero integrar pagar.me ao WCFM

**Comment by RafaMelazzo** [comment]
Olá @AlissonIC, @jfernando1599 e @carloserocha! Tudo bem?

Essa funcionalidade está no nosso backlog e deverá ser priorizada ainda este ano. Vou atualizando vocês quando houver mais informações.

Obrigado!

**Comment by jfernando1599** [comment]
Grato @RafaMelazzo preciso muito da integração com o WCFM e split de pagamento. Acho que ate o momento so tem Dokan

**Comment by chrisanjos** [comment]
Olá, @AlissonIC , @jfernando1599 e @carloserocha ! tudo bem?
Sou product manager aqui do time Pagar.me e estou estudando a solução, estariam interessados um papo para discutirmos a solução ideal? Se sim, me deixem um e-mail para contato por favor ou se preferirem, podem entrar em contato pelo nosso e-mail: opensource@pagar.me
Agradeço desde já pela disponibilidade e feedbacks!
Abraços.

**Comment by jfernando1599** [comment]
Olá sim por favor entrar em contato comigo no email ***@***.***
tenho um projeto com várias lojas que precisam urgente deste módulo

Em ter., 24 de out. de 2023 às 15:52, chrisanjos ***@***.***>
escreveu:

**Comment by AlissonIC** [comment]
Enviei um e-mail aqui para vocês, no meu caso eu apliquei uma modificação adicionando um filtro no json enviado e funcionou para min.

**Comment by RafaMelazzo** [comment]
Boa tarde @AlissonIC, @jfernando1599  e @carloserocha! Tudo bem?

Nós adicionamos filtros para configuração e transação de split de pagamento (marketplace) na última versão do nosso plugin (3.3.0). Segue link da [documentação](https://github.com/pagarme/woocommerce/blob/master/docs/filters-actions/split.md) para mais detalhes.

Espero que ajude! Muito obrigado por contribuírem conosco. Abraços!

**Comment by luiseduardobraschi** [comment]
@RafaMelazzo  Fiz uma observação sobre a implementação na PR. Não tem como saber quais são os valores e, no caso de marketplaces como Dokan e WCFM, saber quem é o vendedor sem passar a referência do pedido.

https://github.com/pagarme/woocommerce/pull/416#issuecomment-2181436300
