### ISSUE TITLE
Atualização para compatibilidade com HPOS

### ISSUE THREAD

**Issue by faelmarcondeli** [pagarme/woocommerce#259]
Olá,
Primeiro gostaria de agradecer por finalmente agora na versão 3.0 do plugin ele estar funcionando como nunca esteve, funcionando bem no caso.

Como nem tudo é ótimo, gostaria de comunica-los que:
Esses dias a equipe responsável pelo Woocommerce se manifestou no sentido de que no ano que vem eles não vão mais utilizar as antigas tabelas do WordPress para a gravação dos dados do Woo. Ou seja, o plano deles é de dar suporte apenas para o HPOS.

https://woocommerce.com/document/high-performance-order-storage/

Como esse plugin ainda não foi atualizado para essa forma de gravação de dados e suas respectivas tabelas, uma boa idéia seria utilizar essa versão 3.0 como base para uma nova versão que o torne compatível com as futuras mudanças.

**Comment by fabiano-mallmann** [comment]
Olá @faelmarcondeli , tudo bem?

Agradecemos o feedback e por contribuir para tornar nosso plugin cada vez melhor! 

Adicionamos essa  tarefa em nosso backlog para priorizar assim que possível.

**Comment by faelmarcondeli** [comment]
Nenhuma novidade pessoal?
Dos plugins relevantes para Woocommerce o único plugin ainda não compatível é o de vocês.

**Comment by fabiano-mallmann** [comment]
@faelmarcondeli, já está na esteira de testes do time, irá ser disponibilizado na próxima versão.

**Comment by faelmarcondeli** [comment]
Maravilha. 👏👏 Muito bom.

**Comment by faelmarcondeli** [comment]
Excelente pessoal, já recebi a atualização e está funcionando certinho. Parabéns pelo comprometimento...
