### ISSUE TITLE
Suporte a trial

### ISSUE THREAD

**Issue by tiagopapile** [pagarme/woocommerce#266]
Olá a todos,

Efetuei alguns testes e não foi possível finalizar uma compra com uma assinatura que oferece um període de testes.

O suporte a trial nas assinaturas está no roadmap de desenvolvimento do plugin? Se sim, teriam alguma previsão?

Obrigado.

WooCommerce 7.8.2
WooCommerce Subscriptions 4.8.1
Pagar.me módulo para Woocommerce 3.1.1

**Comment by mauriciohaygert** [comment]
Ola @tiagopapile 

Realmente o Plugin Pagar.me não esta finalizando o pedido com período de teste.
Vamos colocar em nosso desenvolvimento com prioridade.

Obrigado pela sua ajuda.

**Comment by mateus-picoloto** [comment]
Bom dia @tiagopapile, tudo bem?

Lançamos o suporte ao trial nas assinaturas na versão [3.1.3](https://github.com/pagarme/woocommerce/releases/tag/3.1.3) do plugin.

Muito obrigado!

**Comment by tiagopapile** [comment]
Valeu pelo empenho de vocês, estou utilizando o plugin em alguns clientes e está funcionando muito bem.

Parabéns!
