### ISSUE TITLE
Notice na carteira

### ISSUE THREAD

**Issue by filgduarte** [pagarme/woocommerce#282]
### Status

O plugin está com um notice na página da conta do usuário, na aba "Carteira".

Dei uma pesquisada e vi que o problema está no arquivo **src/Block/Account/Wallet.php** no método **addDataToJs**, onde a função **wp_localize_script** é chamada com uma string como último argumento. O ideal é substituír esse argumento por um array ou utilizar a função wp_add_inline_script(), como sugerido pelo notice.

### Código atual

```
private function addDataToJs()
    {
        wp_localize_script(
            'pagarme_scripts_wallet',
            'apiRoute',
            $this->getApiRoute() /* Deveria ser um array */
        );
        wp_localize_script(
            'pagarme_scripts_wallet',
            'dataSwal',
            $this->getSwalData() /* Deveria ser um array */
        );
    }
```

### Código corrigido

```
private function addDataToJs()
    {
        wp_localize_script(
            'pagarme_scripts_wallet',
            'apiRoute',
            array( $this->getApiRoute() )
        );
        wp_localize_script(
            'pagarme_scripts_wallet',
            'dataSwal',
            array( $this->getSwalData() )
        );
    }
```

### Logs / Stack trace

```
Notice: A função WP_Scripts::localize foi chamada incorretamente. O parâmetro $l10n deve ser um array. Para passar um dado arbitrário para os scripts, use a função wp_add_inline_script() ao invés. Leia como [Depurar o WordPress](https://wordpress.org/documentation/article/debugging-in-wordpress/) para mais informações. (Esta mensagem foi adicionada na versão 5.7.0.) in /home/u881579658/domains/decoreasypapel.com/public_html/wp-includes/functions.php on line 5905
```

**Comment by RafaMelazzo** [comment]
Bom dia @filgduarte! Tudo bem?

Obrigado por contribuir. Nós incluiremos sua correção na próxima atualização. Ou, se preferir, crie um pull request com essa alteração para contribuir com o projeto :smile: 

Muito obrigado!

**Comment by mateus-picoloto** [comment]
Boa tarde @filgduarte, tudo bem?

Adicionamos a correção na ultima versão do plugin.

Muito obrigado!
