### ISSUE TITLE
Sugestão: Possibilidade de feature de pagamentos recorrentes

### ISSUE THREAD

**Issue by Pedroavl** [pagarme/woocommerce#284]
```
Please use the following template to submit your issue. 
Following this template will allow us to quickly investigate and help you with your issue. 
Please be aware that issues which do not conform to this template may be closed. 

DO NOT FORGET TO REMOVE THIS BLOCK
```

### Status

BUG REPORT / TASK

### Checklist

Add checklist if this is a task

- [] Add recurrent payment feature subscriptions

### Steps

1. First step
2. Second step
3. Third step

### Expected behaviour

How do you think the program should work? Add screenshots and code blocks if necessary.

### Actual behaviour

How does the program work in its current state?

### Environment

You may write here the specifications like the version of the project, services, operating system, or hardware if applicable.

### Logs / Stack trace

```
Insert your log/stack trace here
```

**Comment by Pedroavl** [comment]
Haveria essa possibilidade?

**Comment by RafaMelazzo** [comment]
Boa tarde @Pedroavl! Tudo bem?

Caso deseje utilizar a função de recorrência, nosso plugin é compatível com o [WooCommerce Subscriptions](https://woocommerce.com/products/woocommerce-subscriptions/).

Obrigado!
