### ISSUE TITLE
Hook para adicionar objeto 'split' ao objeto 'payments'

### ISSUE THREAD

**Issue by uiliw** [pagarme/woocommerce#301]
Tenho um projeto que não é necessariamente um marketplace onde os vendors poderiam gerenciar pedidos e vendas por conta própria, mas o dono da loja cadastra produtos e atribui um usuário a este produto que possui um valor de comissão configurada neste usuário.

Então minha ideia de projeto que vejo como relativamente simples seria apenas criar um custom meta no editor do produto para informar quem é o fornecedor deste produto (dropdown de users) e em users setaria a porcentagem de comissão da loja em um user_meta.

Ao criar um user, no form de cadastro solicito os dados para criar a conta de recebedor no pagarme com a api https://docs.pagar.me/reference/criar-recebedor-1 e já salva o recipient_id em custom meta do usuário.

Portanto no checkout ao criar um pedido usando o gateway do pagar.me adicionaria antes de enviar pra pagarme o objeto split no objeto payments com amount, recipient_id (coletado na user_meta), etc.. (aqui eu trataria se tiver mais de 1 produto com recebedores diferente e calcularia quando cada um recebe pra montar o array)

Relatórios e outras funcionalidades que os plugins de marketplace oferecem não seria necessário para mim, por isso estou pensando nesta ideia simples, quem sabe criaria depois uma tabelinha de saldo pra cada recebedor usando a api https://docs.pagar.me/reference/saldo-2.. enfim..

Conseguem me apontar o melhor caminho para adicionar estes dados de split junto com o pedido?

Haveria algum hook para adicionar um array do objeto split com os dados do recebedor, valor etc?

Algo do tipo:

```
add_action( 'woocommerce_new_order', 'add_split_to_order',  1, 1  );
function add_split_to_order($order_id) {
  // adiciona o split e lógica explicada anteriormente
}
```

**Comment by uiliw** [comment]
@v-verner

Confirmando um exemplo simples usando o seu filtro seria algo assim né?

```
// Função para adicionar split payment ao pedido
function adicionar_split_payment_pagarme($orderRequest, $order) {
    // Exemplo de verificação: verifique se o valor do pedido é maior que um determinado valor
    $order_total = $order->get_total();
    if ($order_total >= 1000) {
        // Adicione informações de split payment ao pedido
        $orderRequest->payments[0]->split = [
            new \PagarmeCoreApiLib\Models\CreateSplitRequest(),
            new \PagarmeCoreApiLib\Models\CreateSplitRequest()
        ];

        $orderRequest->payments[0]->split[0]->recipientId = "rp_ExAmPlExxxxxxxxx";
        $orderRequest->payments[0]->split[0]->amount = 500; // valor em centavos
        $orderRequest->payments[0]->split[0]->type = "flat";

        $orderRequest->payments[0]->split[1]->recipientId = "rp_xxxxxxxxxExAmPlE";
        $orderRequest->payments[0]->split[1]->amount = 500; // valor em centavos
        $orderRequest->payments[0]->split[1]->type = "flat";
    }

    return $orderRequest;
}

add_filter('pagarme/createOrder/orderRequest', 'adicionar_split_payment_pagarme', 10, 2);

```

**Comment by v-verner** [comment]
Acredito que funcione, eu confesso que pra validar minha regra de negócio aqui eu coloquei as regras de split como uma array simples, sem implementar a classe CreateSplitRequest. Segue exemplo reduzido abaixo


    $splitOrders = []; // regra de negócio local
    $splitRules  = [];
    $adminAmount = $order->payments[0]->amount;

    foreach ($splitOrders as $receiver) :
      $splitRules[] = [
        'recipient_id'  => $recipientId, // regra de negócio local
        'type'          => 'flat',
        'amount'        => $receiverAmount, // regra de negócio local
        'options'       => [
          'charge_processing_fee' => false,
          'liable'                => false,
          'charge_remainder_fee'  => false,
        ]
      ];

      $adminAmount -= $receiverAmount;
    endforeach;

    $splitRules[] = [
      'recipient_id'  => $adminRecipientId, // regra de negócio local
      'type'          => 'flat',
      'amount'        => $adminAmount,
      'options'       => [
        'charge_processing_fee' => true,
        'liable'                => true,
        'charge_remainder_fee'  => true,
      ]
    ];

    $order->payments[0]->split = $splitRules;

    return $order;

**Comment by mateus-picoloto** [comment]
Boa tarde @uiliw, tudo bem?

No momento não possuímos uma solução para isso. A solução do @v-verner funciona conforme mencionado anteriormente. Porém não podemos aplicar aqui, pois está em um código de um outro projeto utilizado por outras plataformas que é o [ecommerce-module-core](https://github.com/pagarme/ecommerce-module-core/).

Estamos analisando para no futuro adicionarmos actions e filters para facilitar esse tipo de customização.

Muito obrigado!

**Comment by RafaMelazzo** [comment]
Boa tarde @uiliw e @v-verner! Tudo bem?

Nós adicionamos filtros para configuração e transação de split de pagamento (marketplace) na última versão do nosso plugin (3.3.0). Segue link da [documentação](https://github.com/pagarme/woocommerce/blob/master/docs/filters-actions/split.md) para mais detalhes.

Espero que ajude! Muito obrigado por contribuir conosco. Abraços!
