### ISSUE TITLE
Campos obrigatórios após updated_checkout no cartão de crédito

### ISSUE THREAD

**Issue by felipelguimaraes** [pagarme/woocommerce#319]
Um bug que impossibilita finalização do checkout para os clientes:
Quando um cliente muda o método de entrega, ou atualiza algum dado, que roda o updated_checkout, mesmo com os dados do cartão nos campos do formulário, ocorre o erro de campos obrigatórios. 
Imagino que o problema seja no card.js que foi atualizado algumas vezes mas pelo jeito não corrigiu o erro. Acho que perde as variáveis ao rodar o updated_checkout ou algo do tipo, mas não sou desenvolvedor do plugin então não fui a fundo, porém um cliente precisa dessa correção com urgência.

Já foi reportado na página do plugin:
https://wordpress.org/support/topic/erro-preencha-campo-obrigatorio/
https://wordpress.org/support/topic/preencha-os-campos-obrigatorios-ao-mudar-metodo-de-entrega/

**Comment by mateus-picoloto** [comment]
Boa tarde @felipelguimaraes, tudo bem?

Conforme já informado nesses suportes esse bug foi corrigido na ultima versão.

Muito obrigado!
