### ISSUE TITLE
PHP: Meta dados genéricos com métodos add/update/get não devem ser utilizados para meta dados internos

### ISSUE THREAD

**Issue by alexbeeeee** [pagarme/woocommerce#328]
Olá, migrei para PHP8.2 e HPOS e aparecerem muitos erros PHP no log

Motivo : uso indevido de get_meta(xxxx) para recuperar meta-dados internos como _billing_address_1, etc...
A correção é simples : em vez de usar $order->_..._... para acessar a meta key, é preciso usar os getters que são as funções get_..._...($order)

Exemplo de entrada do log :
php: is_internal_meta_key was called incorrectly. Meta dados genéricos com métodos add/update/get não devem ser utilizados para meta dados internos, incluindo "**_billing_address_1**". Use os getters e setters. Backtrace: require('wp-blog-header.php'), require_once('wp-includes/template-loader.php'), do_action('template_redirect'), WP_Hook->do_action, WP_Hook->apply_filters, WC_AJAX::do_wc_ajax, do_action('wc_ajax_checkout'), WP_Hook->do_action, WP_Hook->apply_filters, WC_AJAX::checkout, WC_Checkout->process_checkout, WC_Checkout->process_order_payment, Woocommerce\Pagarme\Controller\Gateways\AbstractGateway->process_payment, Woocommerce\Pagarme\Model\Checkout->process, Woocommerce\Pagarme\Controller\Orders->create_order, Pagarme\Core\Kernel\Services\OrderService->createOrderAtPagarme, Pagarme\Core\Kernel\Services\OrderService->extractPaymentOrderFromPlatformOrder, Woocommerce\Pagarme\Concrete\WoocommercePlatformOrderDecorator->getCustomer, Woocommerce\Pagarme\Concrete\WoocommercePlatformOrderDecorator->getRegisteredCustomer, Woocommerce\Pagarme\Helper\Utils::build_customer_address_from_order, Woocommerce\Pagarme\Model\Meta->__get, Woocommerce\Pagarme\Model\Meta->get_property, Woocommerce\Pagarme\Model\Meta->get_meta, WC_Data->get_meta, WC_Data->is_internal_meta_key, wc_doing_it_wrong. This message was added in version 3.2.0.

No log acima, a função build_customer_address_from_order recupera o endereço usando a expressão 
**$order->billing_address_1**. O correto é usar **$order->get_billing_address_1()**, o famoso "getter" do woocommerce 
(woocommerce / includes /class-wc-order.php)

Os erros no log aparecem para todas a meta-key internas dos pedidos (são muitos erros)
O último é mais grave, a função process_payment atualiza o _transaction_id do pedido usando $order->transaction_id enquanto deveria usar a função $order->set_transaction_id() e $order->save()

São uns 20 erros assim mas não é difícil resolver, basta corrigir em 3 arquivos : Utils.php, Checkout.php e WoocommercePlatformOrderDecorator.php

**Comment by mateus-picoloto** [comment]
Boa tarde @alexbeeeee, tudo bem?

Conforme informado na issue #276, iremos colocar na nossa fila de desenvolvimento e assim que priorizarmos e desenvolvermos essa correção voltamos aqui para avisarmos você. Caso queira, também pode criar um PR com essa correção que iremos revisar e aprovar.

Muito obrigado!
