### ISSUE TITLE
On mobile (iPhones mainly), paste event is not triggering the brand/card validation

### ISSUE THREAD

**Issue by eduardobattisti** [pagarme/woocommerce#330]
### Status

BUG REPORT

### Steps

1. On a mobile phone, using a browser like Chrome, paste some credit card number on the checkout.
2. The brand validation won't work like there is no number.
3. It will throw an error when trying to checkout.

### Expected behavior

Validate the credit card when it is pasted.

### Actual behavior

When the credit card is pasted it isn't validated and the same behavior happens when the payment method is changed.
Ex:
If I fill in all the credit card information misclick other payment methods and back to the credit card, I need to insert again the data or trigger some event on the card number to revalidate it.

### Environment

WordPress 6.3.2
Apparently, the error occurs mainly on iPhones.

**Comment by mateus-picoloto** [comment]
Boa tarde @eduardobattisti, tudo bem?

Muito obrigado por relatar esse problema e já fazer um PR com a correção! Iremos lançar ela na nossa próxima versão, assim que lançarmos avisamos aqui.

**Comment by mateus-picoloto** [comment]
Boa tarde @eduardobattisti, tudo bem?

Foi publicado na ultima versão a sua correção.

Muito obrigado!
