### ISSUE TITLE
Erro quando usuário digita nome com caracter especial (ç, ã, é, etc..)

### ISSUE THREAD

**Issue by odirlon** [pagarme/woocommerce#356]
```
Please use the following template to submit your issue. 
Following this template will allow us to quickly investigate and help you with your issue. 
Please be aware that issues which do not conform to this template may be closed. 

DO NOT FORGET TO REMOVE THIS BLOCK
```
Pessoal, está dando uma mensagem na tela para o usuário corrigir, não seria mais inteligente limpar esses dados ao enviar para o Pagar-me?

**Comment by mateus-picoloto** [comment]
Bom dia @odirlon, tudo bem?

Iremos colocar na nossa fila de desenvolvimento a alteração para não deixar o usuário digitar carácter especial nesse campo e assim que priorizarmos e desenvolvermos essa correção voltamos aqui para avisarmos você. Caso queira, também pode criar um PR com essa correção que iremos revisar e aprovar.

Muito obrigado!

**Comment by RafaMelazzo** [comment]
Boa tarde @odirlon! Tudo bem?

Efetuamos essa correção, impedindo que o usuário insira acentuação no campo do nome. Essa alteração será lançada na próxima atualização, mas se quiser adiantar no seu site, pode pegar a [branch develop](https://github.com/pagarme/woocommerce/tree/develop). Até o momento ela tem apenas essa correção a mais.

Obrigado por nos informar desse problema!

**Comment by odirlon** [comment]
Pessoal, ficou perfeito. Obrigado!
