### ISSUE TITLE
Missing number in customer address | Exception code: 0

### ISSUE THREAD

**Issue by tiagopapile** [pagarme/woocommerce#377]
# Bug

Olá,

Estou com um problema na finalização de pedidos de um site. Há clientes que não possuem número em seu endereço, como esse campo está como obrigatório, acabam informando o número 0. Com o pedido não consegue ser criado na Pagar.me e é apresentado que a transação falhou para o cliente.

### Descrição
Quando um cliente informa um número de endereço igual a 0, o pedido não é criado e retorna um erro.

### Como reproduzir
Ao preencher o cadastro de endereço na finalização de compra, inserir "0" no campo número no formulário de endereço.

### Evidências
```
Order.ERROR: Order #131977 : Missing number in customer address | Exception code: 0
Version: m: 3.1.7 c: 2.1.0 p:  Wordpress/6.2.2 Woocommerce/7.7.2 
```

**Comment by fabiano-mallmann** [comment]
Olá @tiagopapile, tudo certo?
Obrigado por contribuir!
Vamos realizar a correção e logo voltamos aqui para lhe dar um feedback!

**Comment by valeriosouza** [comment]
Nada disso? recebo erro "message": "validation_error | billing | \"value\" is required" em toda compra de cartao

**Comment by mateus-picoloto** [comment]
@tiagopapile lançamos uma [versão com essa correção hoje](https://github.com/pagarme/woocommerce/releases/tag/3.2.2).

@valeriosouza poderia abrir uma nova issue detalhando melhor o problema e como reproduzir ele para que possamos validar o problema?

**Comment by tiagopapile** [comment]
@mateus-picoloto obrigado :)
