### ISSUE TITLE
Redução duplicada de estoque

### ISSUE THREAD

**Issue by tiagopapile** [pagarme/woocommerce#380]
# Bug

Olá,

Estou com um problema de redução duplicada de estoque em um site. Não consegui identificar exatamente o problema, porém acredito que o uso de uma função do WooCommerce no plugin possa ter alguma relação.

### Descrição
Analisando os plugins instalados no site, identifiquei que o plugin da Pagar.me utiliza a função `wc_reduce_stock_levels()`. Essa função faz a redução do estoque sem verificar se o mesmo já foi feito para o pedido.

Creio que o ideal seria utilizar a função `wc_maybe_reduce_stock_levels()`, que faz a verificação necessária para então reduzir ou não o estoque.

### Como reproduzir
Foram apenas em poucos pedidos aleatórios, não consegui reproduzir com exatidão :(.

**Comment by mateus-picoloto** [comment]
Olá @tiagopapile, tudo certo?

Vamos colocar a correção na nossa fila de desenvolvimento e assim que corrigido retornamos aqui para avisa-lo.

Caso queira, também pode criar um PR com essa correção que iremos revisar e aprovar.

Muito obrigado!

**Comment by tiagopapile** [comment]
Olá, @mateus-picoloto.

Criei o PR  #381 para esse ajuste. Por favor, avise-me se está adequado ao padrão do repositório, tentei seguir os guias de contribuição aqui apresentados.

Obrigado :)

**Comment by mateus-picoloto** [comment]
Olá @tiagopapile,

Está no padrão sim, iremos revisar, testar e caso tudo certo lançamos em uma próxima versão.

Muito obrigado pela contribuição!

**Comment by mateus-picoloto** [comment]
Olá @tiagopapile,

Lançamos hoje a versão [3.2.0](https://github.com/pagarme/woocommerce/releases/tag/3.2.0) com a sua correção deste problema. Estarei fechando a issue.

Novamente muito obrigado pela contribuição!
