### ISSUE TITLE
[Link de pagamento] Viabilizar pagamento via Pagamento Manual

### ISSUE THREAD

**Issue by fabiano-mallmann** [pagarme/woocommerce#419]
Possibilitar pagamento no checkout do link de pagamento.

**Comment by mateus-picoloto** [comment]
Em desenvolvimento

**Comment by mateus-picoloto** [comment]
Abaixo segue as evidências de ambiente local:

### Não exibir nossos meios de pagamento para Pagamento Manual de visitante

https://github.com/pagarme/woocommerce/assets/38541352/2b77e0b8-78b9-4953-a3e8-074b39de115e

### Pagamento Manual com Boleto

https://github.com/pagarme/woocommerce/assets/38541352/bc076ad8-eaf2-4bd0-90a5-ded058edfe67

### Pagamento Manual com multimeios (Boleto e Cartão de Crédito)

https://github.com/pagarme/woocommerce/assets/38541352/8de5f4d5-ebaa-425d-9f14-eeb6abed4f13

### Pagamento Manual com Cartão de Crédito (Padrão)

https://github.com/pagarme/woocommerce/assets/38541352/227dd4e3-b325-48a3-a6bc-7b53c7940d01

### Pagamento Manual com Cartão de Crédito (Carteira)

https://github.com/pagarme/woocommerce/assets/38541352/7ebd64fb-9f92-48df-8b55-f3b6c370d536

### Pagamento Manual com Pix

https://github.com/pagarme/woocommerce/assets/38541352/248e2cf0-cb2d-49fb-ad5b-33939853fef0

### Pagamento Manual com multimeios (2 Cartões)

https://github.com/pagarme/woocommerce/assets/38541352/e38d955e-5dfa-44f8-950a-febf8974b3ba

### Pagamento Manual com Voucher

https://github.com/pagarme/woocommerce/assets/38541352/a706ef92-31c1-45ef-84a7-44060aae3f23

**Comment by RafaMelazzo** [comment]
Concluído na Release #449
