### ISSUE TITLE
[Reembolso] Adicionar informação de estorno no metadata

### ISSUE THREAD

**Issue by fabiano-mallmann** [pagarme/woocommerce#421]
- [ ] Adicionar a linha "refund": "legacy" ao metadata das transações estornadas via antigo botão Pagar.me

Referência:
```json
{
  "moduleVersion": "3.2.1",
  "coreVersion": "2.3.1",
  "platformVersion": " Wordpress/6.5 Woocommerce/8.7.0",
  "saveOnSuccess": "false"
  "refund": "legacy"
}
```

**Comment by RafaMelazzo** [comment]
Não existe nó de metadata no refund da Pagar.me. Implementação não pode ser efetuada.
