### ISSUE TITLE
Nova lógica de juros com problema

### ISSUE THREAD

**Issue by pedroricha** [pagarme/woocommerce#462]
# Bug

### Descrição
Coloco que o cliente pode parcelar em até 12x sem juros, porém com parcela mínima de R$100.
Mas se o pedido fica abaixo de R$100, não aparece nenhuma parcela para o cliente.
Deveria aparecer que ele pode pagar em 1x (a vista)

### Como reproduzir
Colocar um valor mínimo de parcela, e inserir no carrinho um produto com um valor abaixo desse mínimo

### Evidências
![Bug Pagarme](https://github.com/pagarme/woocommerce/assets/47855766/a4e5bf6d-0927-4120-992c-55efab655f62)

**Comment by RafaMelazzo** [comment]
Bom dia @pedroricha! Tudo bem?

Muito obrigado! Vamos corrigir e publicar a correção ainda hoje.

**Comment by RafaMelazzo** [comment]
Olá @pedroricha!

Lançamos a atualização com a correção desse erro. Por favor, atualize nosso plugin para a versão 3.3.2 na sua loja.

Muito obrigado novamente por contribuir!

Abraço!
