### ISSUE TITLE
Informação de número de parcelas

### ISSUE THREAD

**Issue by pedroricha** [pagarme/woocommerce#470]
# Nova funcionalidade

### Descrição
Tenho integração entre Woocommerce e Bling.

Quando o pedido é importado para o Bling, ele traz informação do tipo de pagamento e quantidade de parcelas.

Porém independente do número de parcelas escolhida, está sendo puxado sempre a informação de 1 parcela.

Seria bom conseguir transmitir essa informação do número de parcelas, para conseguir importar automaticamente a forma de pagamento correta.

![image](https://github.com/pagarme/woocommerce/assets/47855766/6c40b11c-3f9e-459c-bfe2-26ed7f39741f)

**Comment by RafaMelazzo** [comment]
Boa tarde @pedroricha! Tudo bem?

Você pode pegar a informação do número de parcelas na tabela de metadados dos pedidos. Se o WooCommerce da sua loja estiver com o **HPOS** _(High-Performance Order Storage)_ habilitado, a tabela com essa informação é a `wp_wc_orders_meta`, caso HPOS esteja desabilitado, o nome da tabela é `wp_postmeta`.

Nessa tabela você precisa buscar na coluna `meta_key` a por `_pagarme_installments_card1` e `_pagarme_installments_card2` _(este último existe apenas se você aceita o método de dois cartões no seu site)_

Espero ter ajudado.

**Comment by pedroricha** [comment]
Boa tarde @RafaMelazzo 

Entrei em contato com o Bling, e eles me responderam o seguinte em relação ao retorno do número de parcelas:

----
"É informar que no campo "meta_data" deve ser preenchido com "Parcelas" e no campo "value" a quantidade de parcelas que devem ser informadas.

Atualmente no campo "meta-data" está vindo uma informação de estoque (conforme print 1) quando na verdade deve vir a informação das parcelas.

Conforme o print 2, é a forma correta que deve vir a informação.

Qualquer dúvida, fico à disposição."

----


Print 1: 
![image](https://github.com/user-attachments/assets/4dce9cd7-a232-4ae6-b783-4b44fd822ccf)


Print 2: 
![image](https://github.com/user-attachments/assets/12eddab9-90b9-4c03-85ad-c5a02569b0d1)

----

Faz sentido isso que eles passaram?

att

Pedro

**Comment by RafaMelazzo** [comment]
Olá @pedroricha!

Não faz muito sentido o que eles mandaram. Parece que eles estão pegando de outra tabela. Nosso plugin não faz registro de estoque de produtos (essa é uma responsabilidade do WooCommerce).

Primeiro, verifique se nosso plugin está atualizado na sua loja. Essa instrução que passei para você anteriormente se refere a um recurso que foi implementado na [versão 3.1.0](https://github.com/pagarme/woocommerce/releases/tag/3.1.0).

No print abaixo mostro a tabela de um site com HPOS habilitado, ou seja, tabela `wp_wc_orders_meta`. Mas se esse recurso está desabilitado na sua loja, a tabela `wp_postmeta` tem a mesma estrutura com as mesmas informações.

![image](https://github.com/user-attachments/assets/46c72c9a-9ddf-461e-a864-dd92b20e24ee)

Eu filtrei a tabela para exibir apenas as informações que você precisa, com o comando `meta_key like '_pagarme_installments_card%'`, assim ele exibe tanto para os pagamentos com um ou dois cartões. Grifei três exemplos de pedidos diferentes com número de parcelas diferentes, e mais pra baixo marquei um pedido de dois cartões, onde é possível ver dois registros com o mesmo `order_id`, mas com a `meta_key` diferentes, informando as parcelas do cartão 1 e do cartão 2 respectivamente.

São essas as informações que eles precisam buscar.

Pela mensagem que enviaram, eu entendi que eles querem que a gente faça alteração no nosso código, mas não podemos adaptar nosso código para cada ERP do mercado. Se eles não conseguem pegar os dados diretamente, seria necessário o desenvolvimento de um middleware para fornecer os dados da forma que eles precisam.
